package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	. "github.com/dave/jennifer/jen" //lint:ignore ST1001 this is a single file program and dot-importing jen into main is ok
)

func main() {
	pkgDir := flag.String("dir", ".", "directory to scan for protobuf types")
	outputFile := flag.String("output", "marshal_gen.go", "output file name")
	flag.Parse()

	types, err := findProtobufTypes(*pkgDir)
	if err != nil {
		log.Fatalf("Failed to find protobuf types: %v", err)
	}

	if len(types) == 0 {
		log.Println("No protobuf types found")
		return
	}

	// Sort types for consistent output
	sort.Strings(types)

	if err := generateMarshalCode(types, *outputFile); err != nil {
		log.Fatalf("Failed to generate code: %v", err)
	}

	fmt.Printf("Generated marshal implementations for %d types in %s\n", len(types), *outputFile)
}

// findProtobufTypes scans the directory for types that implement protobuf messages
func findProtobufTypes(dir string) ([]string, error) {
	fset := token.NewFileSet()
	types := make(map[string]bool)

	// Parse all .pb.go files
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".pb.go") {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("failed to parse %s: %w", path, err)
		}

		// Look for types that have a ProtoMessage() method
		ast.Inspect(file, func(n ast.Node) bool {
			// Look for method declarations
			funcDecl, ok := n.(*ast.FuncDecl)
			if !ok || funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
				return true
			}

			// Check if method is named ProtoMessage
			if funcDecl.Name.Name != "ProtoMessage" {
				return true
			}

			// Extract the receiver type name
			recv := funcDecl.Recv.List[0].Type
			var typeName string
			switch t := recv.(type) {
			case *ast.StarExpr:
				if ident, ok := t.X.(*ast.Ident); ok {
					typeName = ident.Name
				}
			case *ast.Ident:
				typeName = t.Name
			}

			if typeName != "" {
				types[typeName] = true
			}

			return true
		})

		return nil
	})

	if err != nil {
		return nil, err
	}

	// Convert map to sorted slice
	result := make([]string, 0, len(types))
	for typeName := range types {
		result = append(result, typeName)
	}

	return result, nil
}

// generateMarshalCode generates the marshal/unmarshal implementations
func generateMarshalCode(types []string, outputFile string) error {
	f := NewFile("corepb")

	f.HeaderComment("Code generated by genmarshal. DO NOT EDIT.")

	f.ImportName("encoding", "encoding")

	for _, typeName := range types {
		// Add a comment with the type name
		f.Comment(typeName)
		f.Line()

		// Add compile-time interface checks
		f.Var().Id("_").Qual("encoding", "BinaryMarshaler").Op("=").Parens(Op("*").Id(typeName)).Parens(Nil())
		f.Var().Id("_").Qual("encoding", "BinaryUnmarshaler").Op("=").Parens(Op("*").Id(typeName)).Parens(Nil())
		f.Line()

		// Generate UnmarshalBinary method
		f.Func().Params(
			Id("m").Op("*").Id(typeName),
		).Id("UnmarshalBinary").Params(
			Id("data").Index().Byte(),
		).Error().Block(
			Return(Id("m").Dot("UnmarshalVT").Call(Id("data"))),
		)
		f.Line()

		// Generate MarshalBinary method
		f.Func().Params(
			Id("m").Op("*").Id(typeName),
		).Id("MarshalBinary").Params().Params(
			Id("data").Index().Byte(),
			Id("err").Error(),
		).Block(
			Return(Id("m").Dot("MarshalVT").Call()),
		)
		f.Line()
	}

	// Write to file
	return f.Save(outputFile)
}
